server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://47.94.10.66:3306/group_5?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: xd0630
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
  devtools:
    restart:
      enabled: true
    add-properties: false
  mvc:
    log-request-details: true
#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.app.mapper
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org:
      springframework:
        web:  trace
        boot:
          web:  trace